version: 2.1

jobs:
  run-tests:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: Cleanup workspace
          command: rm -rf ./build ./temp || true
      - run:
          name: Free up disk space
          command: |
            chmod +x ./free_disk_space.sh
            ./free_disk_space.sh
      - run:
          name: Install Docker
          command: |
            apt update
            apt install -y docker.io
      - run:
          name: Run docker build
          command: docker build --pull --rm -f "Dockerfile" -t ticsctests:latest "."
      - run:
          name: Running unit tests
          command: |
            sudo docker run --rm ticsctests bash -c "simnibs_python -m pytest /ti-csc/utils/tests/unit" || \
            (echo "Python unit tests failed. Reviewing logs:" && exit 1)
            sudo docker run --rm ticsctests bash -c "bats /ti-csc/utils/tests/unit/" || \
            (echo "Bash unit tests failed. Reviewing logs:" && exit 1)
      - run:
          name: Running integration tests
          when: always
          command: |
            docker run \
              -v /usr/local/MATLAB/MATLAB_Runtime/R2024a/runtime/glnxa64/libmwmclmcrrt.so.24.1:/usr/local/MATLAB/MATLAB_Runtime/R2024a/runtime/glnxa64/libmwmclmcrrt.so.25.1 \
              --rm ticsctests bash -c "\
              chmod +x /ti-csc/utils/tests/integration/test_analyzerIT.sh && \
              chmod +x /ti-csc/analyzer/field-analysis/process_mesh_files && \
              /ti-csc/utils/tests/integration/test_analyzerIT.sh || \
              (echo 'Integration tests failed. Reviewing logs:' && exit 1)"
      - run:
          name: Cleanup Docker
          when: always
          command: sudo docker system prune --all --force

workflows:
  version: 2
  test_pipeline:
    jobs:
      - run-tests:
          filters:
            branches:
              only:
                - main
