name: Run test suite

on: 
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    run-tests:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - name: Cleanup workspace
              run: rm -rf ./build ./temp || true
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Free up disk space
              run: |
                chmod +x ./free_disk_space.sh
                ./free_disk_space.sh
            - name: Run docker build
              run: docker build --pull --rm -f "Dockerfile" -t ticsctests:latest "."
            - name: Running unit tests
              run: |
                docker run --rm ticsctests:latest sh -c "
                simnibs_python -m pytest /ti-csc/utils/tests/unit/ && 
                bats /ti-csc/utils/tests/unit/"
            - name: Running integration tests
              run: |
                docker run -v /usr/local/MATLAB/MATLAB_Runtime/R2024a/runtime/glnxa64/libmwmclmcrrt.so.24.1:/usr/local/MATLAB/MATLAB_Runtime/R2024a/runtime/glnxa64/libmwmclmcrrt.so.25.1 --rm ticsctests bash /ti-csc/utils/tests/integration/test_analyzerIT.sh
            - name: Cleanup Docker
              if: always()  # Ensures cleanup happens even if prior steps fail
              run: |
                sudo docker system prune --all --force
      