name: Run test suite

on: 
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    run-tests:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - name: Cleanup workspace
              run: rm -rf ./build ./temp || true
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Free up disk space
              run: |
                chmod +x ./free_disk_space.sh
                ./free_disk_space.sh
            - name: Run docker build
              run: docker build --pull --rm -f "Dockerfile" -t ticsctestable:latest "."
            - name: Running unit tests
              run: |
                docker run --rm ticsctestable:latest sh -c "
                  cd ti-csc/ && 
                  simnibs_python -m pytest /ti-csc/utils/tests/unit/ && 
                  bats /ti-csc/utils/tests/unit/"
            - name: Running integration tests
              run: |
                docker run --rm ticsctestable:latest bash /ti-csc/utils/tests/integration/test_analyzerIT.sh
            - name: Cleanup Docker
              if: always()  # Ensures cleanup happens even if prior steps fail
              run: |
                cat /root/fsl_installation_20241212055255.log
                sudo docker system prune --all --force
      