name: Validate Features Branch

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      run: |
        docker --version  # Confirm Docker is installed
        df -h             # Check available disk space
        free -m           # Check available memory

    - name: Build Docker Image
      run: |
        docker build --pull --rm -f "Dockerfile" -t ticsctests:latest "." || \
        (echo "Docker build failed. Reviewing logs:" && exit 1)

    - name: Run Docker Container and Debug
      run: |
        # Run the container interactively for debugging
        docker run --rm -d --name ticsctests_debug ticsctests:latest sleep 30
        # Print top-level directories inside the container
        echo "Top-level directories:"
        docker exec ticsctests_debug ls -1 /
        # Print detailed directory structure for /usr/local inside the container
        echo "Printing directory structure for /usr/local:"
        docker exec ticsctests_debug ls -R /usr/local
        # Search for MATLAB Runtime inside the container
        echo "Searching for MATLAB Runtime in /usr/local/MATLAB:"
        docker exec ticsctests_debug find /usr/local/MATLAB -type d
        echo "Searching for runtime libraries in /usr/local/MATLAB:"
        docker exec ticsctests_debug find /usr/local/MATLAB -name "libmwmclmcrrt.so*" 2>/dev/null || echo "No runtime libraries found."
        # Print environment variables inside the container
        echo "Environment variables:"
        docker exec ticsctests_debug env
        # Clean up the Docker container
        docker rm -f ticsctests_debug

    - name: Run Unit Tests Inside Docker
      run: |
        docker run --rm ticsctests bash -c "simnibs_python -m pytest ti-csc/utils/tests/unit" || \
        (echo "Unit tests failed. Reviewing logs:" && exit 1)

    - name: Run Integration Tests Inside Docker
      run: |
        docker run --rm ticsctests bash -c "\
          chmod +x /ti-csc/utils/tests/integration/test_analyzerIT.sh && \
          /ti-csc/utils/tests/integration/test_analyzerIT.sh || \
          (echo 'Integration tests failed. Reviewing logs:' && exit 1)"

    - name: Cleanup Docker
      if: always()
      run: |
        docker system prune --all --force
